# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 948704c9092b03fdccc0bd9fc92109b1160e787511f6ccc6226a04008f8f32b0c2e384d218386a5f5798d0546629f209ba9926534776e0989a59933354522347

test:
  secret_key_base: f0fa3741b6901ea3d8378f3e1d1d4dcb9b80dcd1f54f64ac730b6b24ac67fa5d9d35bc8c559fb2398c776db15bc2610d6a22cfa00081440e1d49849d0ba0bbf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
